[FEATURE] V1.0.5 Set wp_remote_post method as default to POST data to…
irvinlim/acf-recaptcha pull request #14
Opened 2017-01-26 09:41 UTC by ramonfincken

2017-01-26 10:11 UTC, irvinlim requested changes
Hi, thank you for this! I appreciate it.

I see that you have created a class within the ReCaptcha library folder. I created this plugin 2 years ago when I still was not familiar with Composer, and included the files directly into this repository. However, for the purposes of separating WordPress code from original library code, I think that it is better if we placed this `WP.php` file somewhere else, like `includes/WPHttpRequestMethod.php`.

Anyway, still thank you for this.

2017-01-26 10:11 UTC, irvinlim commented on lib/ReCaptcha/ReCaptcha.php
> +            $this->requestMethod = new RequestMethod\WP();
Let's not modify the original library files, perhaps we can pass in the `$requestMethod` in the `ReCaptcha` constructor?

2017-01-26 10:11 UTC, irvinlim commented on readme.txt
> +This plugin does not require CuRL to be enabled on your server.
It should be spelt cURL.

2017-01-26 10:11 UTC, irvinlim commented on acf-recaptcha-v5.php
> +		$api = new \ReCaptcha\ReCaptcha($field['secret_key']); // FIXME : select field for request method?
We should pass in the `new RequestMethod\WP()` object in this constructor call.

2017-01-26 10:11 UTC, irvinlim commented on README.md
> +WordPress wp_remote_post usage in WP Class written by Ramon Fincken (v 1.0.5)
Would appreciate it if the Markdown was written properly! Single newlines are not displayed in Markdown.

Perhaps you can create a **Contributors** section? Thanks!

2017-01-26 10:11 UTC, irvinlim commented on README.md
> +This plugin does not require CuRL to be enabled on your server
You can just remove this line actually.

2017-01-31 14:17 UTC, ramonfincken commented
I will check on those!

2017-02-02 14:40 UTC, ramonfincken commented on lib/ReCaptcha/ReCaptcha.php
> +            $this->requestMethod = new RequestMethod\WP();
Done

2017-02-02 14:41 UTC, ramonfincken commented on readme.txt
> +This plugin does not require CuRL to be enabled on your server.
done

2017-02-02 14:41 UTC, ramonfincken commented on acf-recaptcha-v5.php
> +		$api = new \ReCaptcha\ReCaptcha($field['secret_key']); // FIXME : select field for request method?
done

2017-02-02 14:41 UTC, ramonfincken commented on README.md
> +This plugin does not require CuRL to be enabled on your server
indeed, done

2017-02-02 14:45 UTC, ramonfincken commented on README.md
> +WordPress wp_remote_post usage in WP Class written by Ramon Fincken (v 1.0.5)
done, i didn't tag it 1.0.6, that's up to you

2017-02-03 08:03 UTC, closed without merging